version: '3'
services:
  web:
    build: .
    ports:
      - "7000:7000"
  db:
    image: postgres  # Corrected to lowercase "postgres"
    environment:
      POSTGRES_ROOT_PASSWORD: POSTGRES_ROOT_PASSWORD
    volumes:
      - db-data:/foo

volumes:
  db-data:

  # to run : docker-compose up